eth1_client_name: ethereumjs
eth1_image_name: parithoshj/ethereumjs:merge-59d1fdc

eth1_github_external_user_pubkeys:
  - holgerd77
  - ryanio
  - jochem-brouwer
  - acolytec3

eth1_memory: 8000M
eth1_kernel_memory: 8500M

# websocket with upgrade
eth1endpoint_ws: http://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"

eth1_start_args: >
  --datadir=/eth1data
  --gethGenesis=/networkdata/genesis.json
  --rpc --rpcEngine --rpcEnginePort=8545 --rpcStubGetLogs --rpcDebug
  --loglevel={{ beacon_log_level | lower }}
  {% if (eth1_bootnode_enode is defined) and eth1_bootnode_enode %}
  --bootnodes "{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}
  --extIP={{ansible_host}}

eth1_user_id: "1000:1000"
